name: CI
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK 22
      uses: actions/setup-java@v5
      with:
        java-version: '22'
        distribution: 'zulu'
        cache: sbt
    - run: sbt test
